apiVersion: apps/v1
kind: Deployment
metadata:
  name: articles-ui
spec:
  selector:
    matchLabels:
      app: articles-ui
  replicas: 1
  template:
    metadata: 
      labels:
        app: articles-ui
    spec:
      containers:
        - name: articles-ui
          image: articles-ui:v4
---
apiVersion: v1
kind: Service
metadata:
  name: articles-ui
spec:
  type: NodePort
  selector:
    app: articles-ui
  ports:
    - name: articles-ui
      port: 3000
      targetPort: 3000
      nodePort: 31003
